#depth parameters

focus: 381.362467                        #focal length in meters 
baseline: 0.05                      #in meters
block_size: 9                      #parameter for stereo matcher
num_disparities: 32                 #parameter for stereo matcher 
                                    #CAUTION: use factor of 16.

use_disparity_filter: True          #If set to true, a filter is applied 
                                    #to smoothen disparity maps
                                    #The filter increases computation
                                    #to a large extent.
                                    
lambda: 8000                        #parameter for disparity filter
sigma: 6                            #parameter for disparity filter 